### ISSUE TITLE
Having trouble getting extensions to work

### ISSUE THREAD

**Issue by alinanevins** [mkhairi/jquery-datatables#10]
Basic datatables is working great. However, I can't seem to get any of the extensions to work. For example, I added this to the head:
`$("#sortable").DataTable( {
      fixedHeader: true
    });`
But fixed headers doesn't work, nothing seems to change. This is the same behavior I'm getting with all of the extensions. 
I installed this gem using your autoinstall, and enabled the appropriate extensions in datatables.scss.

**Comment by mkhairi** [comment]
hi @alinanevins, it should be work. did you get any error on web console?.  Please check on enabled extensions on datatables.js too. And also if you use fixed navigation style on you layout, you should pass `headerOffset` option.

**Comment by alinanevins** [comment]
Thanks @mkhairi, I missed the part about enabling the extension on datatables.js. That did the trick. 
Where should I pass the `headerOffset` option?

**Comment by mkhairi** [comment]
@alinanevins, see https://datatables.net/reference/option/fixedHeader.headerOffset
