### ISSUE TITLE
Sorting icons not showing up

### ISSUE THREAD

**Issue by DavidMoritz** [mkhairi/jquery-datatables#11]
I noticed that it is pointing to the non-hashed versions of the sorting icons. Also, I am aware that newer versions of datatables actually embed the icons directly rather than use external files. Is there any way this can be resolved?

**Comment by mkhairi** [comment]
hi @DavidMoritz, see [this file](https://github.com/mkhairi/jquery-datatables/blob/12aa184b656f82bf1190ee1a7e796e08afafb69d/lib/generators/jquery/datatables/templates/stylesheets/regular.scss.tt#L18)

**Comment by DavidMoritz** [comment]
Thank you for the fast response! This works great! I think you should patch this to latest version.

**Comment by mkhairi** [comment]
c2f678967665bd8d97b0057f68ba82b90fd04204
