### ISSUE TITLE
Removing autoprefixer-rails as runtime dependency?

### ISSUE THREAD

**Issue by zokioki** [mkhairi/jquery-datatables#13]
Would it be a good idea to remove `autoprefixer-rails` as a direct dependency of the gem? It feels like something that should be included by the gem's end user on a case by case basis.

For example, the app I'm pulling this gem into is primarily an internal dashboard and does not require legacy or wide browser support. I currently manually disable AutoprefixerRails as my app has no need for it to be loaded.

Wondering what your thoughts are on this 🙂

**Comment by mkhairi** [comment]
hi @zokioki,  master branch now not depend on `autoprefixer-rails`.

**Comment by zokioki** [comment]
Thanks @mkhairi ! Not sure if you're open to how the gem's versioned, but one thing you can do is add an extra version point for gem-specific changes like these, something like:

```
v1.10.19.x
```

This way you can still have versions pushed out that address any issues in-between `databaseTable`'s releases, while staying in line with the original library's versioning. Let me know what your thoughts are on this.

**Comment by mkhairi** [comment]
Hi @zokioki , ```v1.10.19.1``` published on rubygems.org. Sorry for delayed. Btw, thanks for suggestion. 👍

**Comment by zokioki** [comment]
Thanks a ton @mkhairi , will close issue now 👍
