### ISSUE TITLE
button placement with bs4

### ISSUE THREAD

**Issue by philsmy** [mkhairi/jquery-datatables#18]
Very basic setup with this gem and using bootstrap 4 (all done through the generators here).

Calling a table like this:

```     
$("#dataTables-emails").DataTable({
 dom: "Bfrtip"
});
```

And the buttons and search field are mis-aligned (as are the info and pagination in the footer). 
How to fix this issue?

**Comment by Chrisgo-75** [comment]
@philsmy Hi Phil. Thanks for your youtube videos. Anyways, where did you find that adding "dom: 'Bfrtip'" adds the buttons?

**Comment by Chrisgo-75** [comment]
@philsmy How did you resolve the mis-aligned buttons? When I add the buttons, it covers up the drop-down which allows different numbers of records to be shown.
