### ISSUE TITLE
Hey keep getting this Error 

### ISSUE THREAD

**Issue by DavidG22** [mkhairi/jquery-datatables#4]
`Could not find gem 'jquery-datatables' in any of the gem sources listed in your Gemfile.`
Gem sources seems to be the logical explanation. However I don't see any specific sources in the doc, other than the ones I've always used.

**Comment by mkhairi** [comment]
@DavidG22, that weird. this gem exist in rubygems.org 
https://rubygems.org/gems/jquery-datatables
