### ISSUE TITLE
Problem compiling datatable assets

### ISSUE THREAD

**Issue by sciguy** [mkhairi/jquery-datatables#7]
I had a problem compiling datatable assets (version 1.10.15) using the latest version of sprockets (4.0.0.beta4). I fixed the issue locally by changing the extensions of the css files to scss.

**Comment by JoeyLeadJig** [comment]
To extend on this issue it is specifically related to use of `image-url` in [/app/assets/stylesheets/datatables/dataTables.foundation.css](https://github.com/mkhairi/jquery-datatables/blob/936aa25a1591d4a60185deccd2720e229cd5aa43/app/assets/stylesheets/datatables/dataTables.foundation.css) and [/app/assets/stylesheets/datatables/jquery.dataTables.css](https://github.com/mkhairi/jquery-datatables/blob/936aa25a1591d4a60185deccd2720e229cd5aa43/app/assets/stylesheets/datatables/jquery.dataTables.css)

**Comment by sciguy** [comment]
Yes. For me it was specifically jquery.dataTables.css. But any .css file with image-url could cause a problem.

**Comment by joeyparis** [comment]
I found a solution that did not require me to change any code within the gem. I renamed `app/assets/stylesheets/datatables.css` to `app/assets/stylesheets/datatables.scss` and replaced the sprockets `require` with the sass `@import`. This way I could import the CSS files from the gem, but process them through `sass-rails` to parse the `image-url` tag.

Basically I changed from this:
_app/assets/stylesheets/datatables.css_
```
/*
*= require datatables/jquery.dataTables
*= require datatables/extensions/AutoFill/autoFill.bootstrap
*= require datatables/extensions/Buttons/buttons.bootstrap
*= require datatables/extensions/ColReorder/colReorder.bootstrap
*= require datatables/extensions/FixedColumns/fixedColumns.bootstrap
*= require datatables/extensions/FixedHeader/fixedHeader.bootstrap
*= require datatables/extensions/KeyTable/keyTable.bootstrap
*= require datatables/extensions/Responsive/responsive.bootstrap
*= require datatables/extensions/RowReorder/rowReorder.bootstrap
*= require datatables/extensions/Scroller/scroller.bootstrap
*= require datatables/extensions/Select/select.bootstrap
*/
```
to this:
_app/assets/stylesheets/datatables.scss_
```
@import "datatables/jquery.dataTables";
@import "datatables/extensions/AutoFill/autoFill.bootstrap";
@import "datatables/extensions/Buttons/buttons.bootstrap";
@import "datatables/extensions/ColReorder/colReorder.bootstrap";
@import "datatables/extensions/FixedColumns/fixedColumns.bootstrap";
@import "datatables/extensions/FixedHeader/fixedHeader.bootstrap";
@import "datatables/extensions/KeyTable/keyTable.bootstrap";
@import "datatables/extensions/Responsive/responsive.bootstrap";
@import "datatables/extensions/RowReorder/rowReorder.bootstrap";
@import "datatables/extensions/Scroller/scroller.bootstrap";
@import `"datatables/extensions/Select/select.bootstrap";`
```

**Comment by andy-twosticks** [comment]
@joeyparis Not working for me, I'm afraid.  I just get 

    ActionView::Template::Error (File to import not found or unreadable: datatables/jquery.dataTables.

...which seems reasonable since those files are in the gem?

**Comment by mkhairi** [comment]
thanks for reporting issue 👍. this issue will be be fix next release 🙇 . the best solution for current version, please covert to scss file as mentioned by @joeyparis  above.
