### ISSUE TITLE
Long loading time

### ISSUE THREAD

**Issue by yewness** [mkhairi/jquery-datatables#9]
I have about 1000 records to load in a go. When I was loading it, it was taking around 4-5 seconds to load each time. Is there any way to put it into ajax on loading? The setting in datatable seems to prompt errors when I add them.

**Comment by mkhairi** [comment]
You need to enable server-side pagination on your app. 
Take a look at gem [ajax-datatables-rails](https://github.com/jbox-web/ajax-datatables-rails) simple solution.

**Comment by yewness** [comment]
The server side rendering works well, but there's 2 issues:

- Bootstrap 4 styling is not available as part of the preset (which your gem has them configured nicely)
- It's using the datatable gem that has not been updated for 2 years, which it's still using old syntax like fnDestroy() instead of destroy() to clear cached datatable in reloading turbolinks.

![screen shot 2018-04-22 at 12 57 11 am](https://user-images.githubusercontent.com/14829481/39086684-30f006d6-45c8-11e8-8dcf-6323dafeab2f.png)

Since the solution given could not be integrated with your current gem, is there any suggestion you could provide in the meantime?

**Comment by mkhairi** [comment]
@yewness, you  still can use this gem along with ` gem 'ajax-datables-rails'`.  just replace the old one.

**Comment by yewness** [comment]
Yeap, I've got it working. Just need to follow through the steps from ajax datatable then the data will appear in the table.

`
# require both gems
gem 'jquery-datatables'
gem 'ajax-datatables-rails'
`

Perhaps, it would be great if a documentation can be added for this one. Thanks a lot!
